CREATE TYPE genre as ENUM ('fantasy', 'sci-fi', 'modern', 'horror', 'historical', 'superhero', 'post-apocalyptic', 'slice-of-life');
CREATE TYPE frequency AS ENUM ('Twice Weekly', 'Weekly', 'Bi-Weekly', 'Month');
CREATE TYPE duration AS ENUM ('Short 2 to 3 Hours', 'Average 3 to 4 Hours', 'Long 5+ Hours');
CREATE TYPE alignment AS ENUM ('Good', 'Evil', 'Lawful', 'Chaotic', 'Neutral');

CREATE TABLE iF NOT EXISTS profiles (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  userid INTEGER NOT NULL REFERENCES users,
  gamemaster BOOLEAN NOT NULL DEFAULT false,
  genre GENRE NOT NULL,
  romance BOOLEAN NOT NULL DEFAULT false,
  frequency FREQUENCY NOT NULL DEFAULT 'Bi-Weekly',
  duration DURATION NOT NULL DEFAULT 'Average 3 to 4 Hours',
  alignment ALIGNMENT NOT NULL,
  groupsize INTEGER NOT NULL DEFAULT 5,
  pvp BOOLEAN NOT NULL DEFAULT false,
  experience INTEGER,
  gmexp BOOLEAN DEFAULT false,
  playexp BOOLEAN DEFAULT false
);